[package]
name = "beetmash_server"
version.workspace = true
edition.workspace = true
repository.workspace = true
readme.workspace = true
description.workspace = true
documentation.workspace = true

# [dependencies]
# get rust-analyzer to stop complaining by specifying not wasm
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
forky.workspace = true
beetmash_net.workspace = true

extend.workspace = true
anyhow.workspace = true
serde.workspace = true
log.workspace = true
pretty_env_logger.workspace = true

tokio.workspace = true
futures.workspace = true
futures-util.workspace = true
axum = { version = "0.7", features = ["ws"] }
axum-extra = { version = "0.9", features = ["typed-header"] }

headers = "0.4"
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.5", features = ["fs", "trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
sweet.workspace = true
reqwest = { version = "0.11", features = ["json"] }
tokio-tungstenite.workspace = true
