[build]
target = "xtensa-esp32s3-espidf"
target-dir = "target"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = [
	"--cfg",
	"espidf_time64",
] # Extending time_t for ESP IDF 5: https://github.com/esp-rs/rust/issues/110

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU = "esp32s3"
ESP_IDF_VERSION = "v5.2.2"


# Workaround for https://github.com/esp-rs/esp-idf-template/issues/174 
# macos build
CRATE_CC_NO_DEFAULTS = "1"
