[package]
name = "beetmash_template"
version.workspace = true
edition.workspace = true
description = "An example workflow for publishing Bevy apps and scenes to Beetmash."
documentation.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish = true

[dependencies]
beet = "0.0.3"
bevy = "0.14.0"


[[package.metadata.app]]
name = "simple_app"
description = "Simply the Bevy Default Plugins with some serialization & IO helpers."
js_url = "https://beetmash-apps.s3.amazonaws.com/temp/simple_app/main.js"
wasm_url = "https://beetmash-apps.s3.amazonaws.com/temp/simple_app/main_bg.wasm"


[[package.metadata.scene]]
name = "simple_environment"
description = "Simply a light and a 3d camera with a sensible offset."
path = "./scenes/simple_environment.ron"

[[package.metadata.scene]]
name = "simple_scene"
description = "Simply a cube sitting on a circular platform."
path = "./scenes/simple_scene.ron"
# list of scene dependencies, can be string or table specifying `crate_name` and `scene_name`
dependencies = ["simple_environment"]

[[package.metadata.demo]]
name = "simple_demo"
description = "Simply a demo of the `simple_app` and `simple_scene`."
app = "simple_app"
# list of scene dependencies
scenes = [
	{ crate_name = "beetmash_template", scene_name = "simple_scene" }
]