
default:
	just --list --unsorted

build-scenes:
	cargo run --bin export_scenes

run:
	cargo run scenes/my_base_scene.json scenes/my_beautiful_scene.json

pkg *args:
	cargo package --no-verify --allow-dirty {{args}}

wasm-dir:= './target/wasm'

build-web *args:
	cargo build --target wasm32-unknown-unknown --release {{args}}
	rm -rf {{wasm-dir}} || true
	mkdir -p {{wasm-dir}} || true
	wasm-bindgen \
	--out-name main \
	--out-dir {{wasm-dir}} \
	--target web \
	--no-typescript \

deploy-web:
	aws s3 sync {{wasm-dir}} \
	s3://beetmash-apps/temp/beetmash_template \
	--delete