wasm-dir:= './target/web-examples'
web-examples:= 'simple_app'

build-scenes:
	cargo run --example build_scenes

run:
	cargo run --example simple_app simple_scene

pkg *args:
	cargo package --no-verify --allow-dirty {{args}}

web-example-build example *args:
	cargo build --example {{example}} --target wasm32-unknown-unknown --release {{args}}
	mkdir -p {{wasm-dir}}/{{example}} || true
	wasm-bindgen \
	--out-name main \
	--out-dir {{wasm-dir}}/{{example}} \
	--target web \
	$CARGO_TARGET_DIR/wasm32-unknown-unknown/release/examples/{{example}}.wasm \
	--no-typescript \

web-example-deploy example:
	aws s3 sync {{wasm-dir}}/{{example}} \
	s3://beetmash-apps/temp/{{example}} \
	--delete


web-examples:
	rm -rf {{wasm-dir}} || true
	for file in {{web-examples}}; do \
		just web-example-build ${file}; \
		just web-example-deploy ${file}; \
	done

# with-version *args:
# 	@version=$(grep '^version' Cargo.toml | head -1 | awk -F '"' '{print $2}') \
# 	&& just {{args}} $version